// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import Navigation from "@/components/navigation/navigation";
import AnimatedWrapper from "@/components/animated-wrapper";

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body>
        <main className="container mx-auto px-4 py-8">
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
